local ls = require "luasnip"
local s = ls.snippet
local t = ls.text_node

return {
  s({ trig = ";N", dscr = "\\nabla", snippetType = "autosnippet" }, { t "\\nabla" }),
  s({ trig = ";a", dscr = "\\alpha", snippetType = "autosnippet" }, { t "\\alpha" }),
  s({ trig = ";b", dscr = "\\beta", snippetType = "autosnippet" }, { t "\\beta" }),
  s({ trig = ";g", dscr = "\\gamma", snippetType = "autosnippet" }, { t "\\gamma" }),
  s({ trig = ";G", dscr = "\\Gamma", snippetType = "autosnippet" }, { t "\\Gamma" }),
  s({ trig = ";d", dscr = "\\delta", snippetType = "autosnippet" }, { t "\\delta" }),
  s({ trig = ";D", dscr = "\\Delta", snippetType = "autosnippet" }, { t "\\Delta" }),
  s({ trig = ";e", dscr = "\\epsilon", snippetType = "autosnippet" }, { t "\\epsilon" }),
  s({ trig = ";ve", dscr = "\\varepsilon", snippetType = "autosnippet" }, { t "\\varepsilon" }),
  s({ trig = ";z", dscr = "\\zeta", snippetType = "autosnippet" }, { t "\\zeta" }),
  s({ trig = ";h", dscr = "\\eta", snippetType = "autosnippet" }, { t "\\eta" }),
  s({ trig = ";o", dscr = "\\theta", snippetType = "autosnippet" }, { t "\\theta" }),
  s({ trig = ";vo", dscr = "\\vartheta", snippetType = "autosnippet" }, { t "\\vartheta" }),
  s({ trig = ";O", dscr = "\\Theta", snippetType = "autosnippet" }, { t "\\Theta" }),
  s({ trig = ";k", dscr = "\\kappa", snippetType = "autosnippet" }, { t "\\kappa" }),
  s({ trig = ";l", dscr = "\\lambda", snippetType = "autosnippet" }, { t "\\lambda" }),
  s({ trig = ";L", dscr = "\\Lambda", snippetType = "autosnippet" }, { t "\\Lambda" }),
  s({ trig = ";m", dscr = "\\mu", snippetType = "autosnippet" }, { t "\\mu" }),
  s({ trig = ";n", dscr = "\\nu", snippetType = "autosnippet" }, { t "\\nu" }),
  s({ trig = ";x", dscr = "\\xi", snippetType = "autosnippet" }, { t "\\xi" }),
  s({ trig = ";X", dscr = "\\Xi", snippetType = "autosnippet" }, { t "\\Xi" }),
  s({ trig = ";i", dscr = "\\pi", snippetType = "autosnippet" }, { t "\\pi" }),
  s({ trig = ";I", dscr = "\\Pi", snippetType = "autosnippet" }, { t "\\Pi" }),
  s({ trig = ";r", dscr = "\\rho", snippetType = "autosnippet" }, { t "\\rho" }),
  s({ trig = ";s", dscr = "\\sigma", snippetType = "autosnippet" }, { t "\\sigma" }),
  s({ trig = ";S", dscr = "\\Sigma", snippetType = "autosnippet" }, { t "\\Sigma" }),
  s({ trig = ";t", dscr = "\\tau", snippetType = "autosnippet" }, { t "\\tau" }),
  s({ trig = ";f", dscr = "\\phi", snippetType = "autosnippet" }, { t "\\phi" }),
  s({ trig = ";vf", dscr = "\\varphi", snippetType = "autosnippet" }, { t "\\varphi" }),
  s({ trig = ";F", dscr = "\\Phi", snippetType = "autosnippet" }, { t "\\Phi" }),
  s({ trig = ";c", dscr = "\\chi", snippetType = "autosnippet" }, { t "\\chi" }),
  s({ trig = ";p", dscr = "\\psi", snippetType = "autosnippet" }, { t "\\psi" }),
  s({ trig = ";P", dscr = "\\Psi", snippetType = "autosnippet" }, { t "\\Psi" }),
  s({ trig = ";w", dscr = "\\omega", snippetType = "autosnippet" }, { t "\\omega" }),
  s({ trig = ";W", dscr = "\\Omega", snippetType = "autosnippet" }, { t "\\Omega" }),
}
